name: Update README

on:
  schedule:
    - cron: "0 0,10 * * *" # AM 9:00 and PM 7:00 in JST
  workflow_dispatch:

jobs:
  run-main-rb:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Run update_readme.rb
        run: ruby update_readme.rb

      - name: Git Setting
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit and push
        run: |
          git add -u
          git commit -m "Update README"
          git push origin main
